# get http://localhost:3001/api/battleRoute/getInitialData

# get http://localhost:3001/api/battleRoute/list

# post http://localhost:3001/api/battleRoute/
# Content-Type: application/json

# {
#     "king":"Mance Rayder"
# }

# get http://localhost:3001/api/battleRoute/count

# get http://localhost:3001/api/battleRoute/stats

# get http://localhost:3001/api/battleRoute/stats
