get http://localhost:3001/api/battleRoute/getInitialData

# get http://localhost:3001/api/battleRoute/list

# post http://localhost:3001/api/battleRoute/
# Content-Type: application/json

# {
#     "king":"Mance Rayder"
# }

# get http://localhost:3001/api/battleRoute/count

# get http://localhost:3001/api/battleRoute/stats

# post http://localhost:3001/api/battleRoute/insertbattle
# Content-Type: application/json

# {
#     "name": "Battle of Deepwood Motte",
#     "year": "298",
#     "battle_number": "9",
#     "attacker_king": "Balon/Euron Greyjoy",
#     "defender_king": "Robb Stark",
#     "attacker_1": "Greyjoy",
#     "attacker_2": "",
#     "attacker_3": " ",
#     "attacker_4": " ",
#     "defender_1": "Stark",
#     "defender_2": " ",
#     "defender_3": " ",
#     "defender_4": " ",
#     "attacker_outcome": "win",
#     "battle_type": "siege",
#     "major_death": "0",
#     "major_capture": "0",
#     "attacker_size": "1000",
#     "defender_size": " ",
#     "attacker_commander": "Asha Greyjoy",
#     "defender_commander": " ",
#     "summer": "1",
#     "location": "Deepwood Motte",
#     "region": "The North",
#     "note": " "
# }